### PR TITLE
Made it work with meteor 1.2

### PR DESCRIPTION
**Pull request by ScyDev**

### CODE REVIEW

**Comment by krishaamer** [comment]
Hey, what's the update on this?

**Comment by ScyDev** [comment]
@tsega Will you merge the pull request?

**Comment by tsega** [comment]
@ScyDev sorry didn't see this PR there, must have slipped! Going through the changes right now ... the only change some people might have an issue with is the use of the fontawesome icons instead of glyphicons. What are you thoughts on that?

**Comment by ScyDev** [comment]
@tsega Glyphicons just didn't work. I would have expected it to be a dependency that is automatically added, but even when I added the bootstrap 3 and glyphicons packages manually, the icons didn't show up and would throw errors on the JS console.

So I replaced them with FA icons, because they work :)

But you can of course discard that if you like.

**Comment by tsega** [comment]
That's strange, what bootstrap package did you use? The icons show up on all of my projects I've used this package in. I use the [twbs:bootstrap](https://atmospherejs.com/twbs/bootstrap) package.

**Pull request merged**
